name: Cleanup GHCR Images

on:
  schedule:
    # Run weekly on Sundays at 2am UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'lazydocker-webui'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'
